{% set name = "django-loginas" %}
{% set version = "0.3.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 080bb6b714cee854739cc7242f2faf9e23f098691bd42ef3fd62e9bc9c5492ad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - loginas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stochastic-technologies/django-loginas/
  summary: An app to add a "Log in as user" button in the Django user admin page.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
