{% set name = "django-loginas" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-loginas-{{ version }}.tar.gz
  sha256: c0edab7396f823940a1d9891cad8741cae2a99ed562768b33bc58e83093c8a99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - loginas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stochastic-technologies/django-loginas/
  summary: An app to add a "Log in as user" button in the Django user admin page.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
