{% set name = "django-loginas" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 10cc5f7bfc1d5835825ef7b6fd007fd7edfd0bf562136f25e0d9904067772a80

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - loginas
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stochastic-technologies/django-loginas/
  summary: An app to add a "Log in as user" button in the Django user admin page.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
